language: python
python:
- '2.7'
install:
- ls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: ubyssey-prd
  default: true
  on:
    branch: cd-gcp
before_install:
- openssl aes-256-cbc -K $encrypted_430686a93cbd_key -iv $encrypted_430686a93cbd_iv
  -in client-secret.json.enc -out client-secret.json -d
