sudo: false
language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_430686a93cbd_key -iv $encrypted_430686a93cbd_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
install:
- pip install -r requirements.txt -t lib/
script:
- echo "No Script to run"
- mv settings-prd.py ubyssey/settings.py
deploy:
  provider: gae
  keyfile: client-secret.json
  project: ubyssey-prd
  default: true
  skip_cleanup: true
  on:
    branch: cd-gcp
