sudo: false
language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_d55f894abbe8_key -iv $encrypted_d55f894abbe8_iv -in client-secret.json.enc -out client-secret.json -d
- export PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/lib"
install:
- pip install -r requirements.txt -t lib/
- pip install requests --upgrade -t lib/
- cd ubyssey/static
- npm install -g gulp
- npm install
script:
- gulp build
after_success:
# clean up node_modules
- rm -rf node_modules
- cd ${TRAVIS_BUILD_DIR}
# use deploy settings
- mv _settings/settings-dpl.py ubyssey/settings.py
- python manage.py collectstatic --noinput
# gzip static files
- find ${TRAVIS_BUILD_DIR}/gcs -type f -exec gzip "{}" \; -exec mv "{}.gz" "{}" \;
# replace deploy settings with production settings
- rm ubyssey/settings.py ubyssey/settings.pyc
- mv _settings/settings-prd.py ubyssey/settings.py
deploy:
  - provider: gcs
    keyfile: client-secret.json
    bucket: ubyssey
    skip_cleanup: true
    acl: public-read
    local-dir: ${TRAVIS_BUILD_DIR}/gcs
    detect_encoding: true
    cache_control: "max-age=31536000"
    on:
      branch: develop
  - provider: gae
    keyfile: client-secret.json
    project: ubyssey-prd
    default: true
    skip_cleanup: true
    on:
      branch: develop
