sudo: false
language: python
python:
- '2.7'
before_install:
- openssl aes-256-cbc -K $encrypted_430686a93cbd_key -iv $encrypted_430686a93cbd_iv
  -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar -xzf secrets.tar.gz
- mv _settings/settings-prd.py ubyssey/settings.py
install:
- pip install -r requirements.txt -t lib/
- pip install requests --upgrade -t lib/
script:
- python -c "import django; print(django.get_version())"
- source ~/virtualenv/python2.7/bin/activate
- python -c "import django; print(django.get_version())"
- python manage.py collectstatic
- ls lib
- ls
deploy:
  provider: gae
  keyfile: client-secret.json
  project: ubyssey-prd
  default: true
  skip_cleanup: true
  on:
    branch: cd-gcp
