# [START runtime]
runtime: custom
env: flex
entrypoint: gunicorn -b :$PORT ubyssey.wsgi

beta_settings:
    cloud_sql_instances: ubyssey-prd-flex:us-central1:ubyssey-prd-flex

manual_scaling:
    instances: 1
# [END runtime]
