runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: .*
  script: ubyssey.wsgi.application
  secure: always
- url: .well-known/acme-challenge/9MinV1w3ZAYOKnlg0x4hEDqDjUbRELhvF0fZ7xFuyIA
  static_files: challenge.txt
  upload: challenge.txt

libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7
- name: ssl
  version: latest

skip_files:
    - lib/PIL*
