runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: ubyssey.wsgi.application
  secure: always
- url: /.well-known
  static_dir: well-known
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7
- name: ssl
  version: latest

skip_files:
    - lib/PIL*
