runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  SECRET_KEY: {{SECRET_KEY}}
  SQL_HOST: {{SQL_HOST}}
  SQL_DATABASE: {{SQL_DATABASE}}
  SQL_USER: {{SQL_USER}}
  SQL_PASSWORD: {{SQL_PASSWORD}}

handlers:
- url: .*
  script: ubyssey.wsgi.application

libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7

skip_files:
    - lib/PIL*
