runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: ubyssey.wsgi

libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7
- name: requests
  version: 2.18.4

skip_files:
    - lib/PIL*
    - lib/requests*
