version: 0.0
os: linux
files:
  - source: ubyssey/
    destination: /var/webapps/staging.ubyssey.ca/app
  - source: manage.py
    destination: /var/webapps/staging.ubyssey.ca/manage.py
  - source: requirements.txt
    destination: /var/webapps/staging.ubyssey.ca/requirements.txt
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
