version: 0.0
os: linux
files:
  - source: manage.py
    destination: /var/webapps/ubyssey
  - source: requirements.txt
    destination: /var/webapps/ubyssey
  - source: _scripts/
    destination: /var/webapps/ubyssey/_scripts/
  - source: ubyssey/
    destination: /var/webapps/ubyssey/ubyssey/
hooks:
  ApplicationStop:
    - location: _scripts/ubyssey_stop.sh
  ApplicationStart:
    - location: _scripts/ubyssey_start.sh
