version: "2.1"
services:
  db:
    build: mysql/
    environment:
      MYSQL_DATABASE: ubyssey
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  gulp:
    build: .
    command: bash -c "cd ubyssey/static && npm install && gulp"
    volumes:
      - .:/ubyssey.ca

  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ubyssey.ca
    volumes_from:
      - gulp
    ports:
      - "8000:8000"
    depends_on:
      - db
    container_name: ubyssey-dev
