version: "2.1"
services:

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    build: mysql/
    environment:
      MYSQL_DATABASE: ubyssey
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

## Starts up static file watcher for ubyssey.ca
  gulp:
    build: .
    command: bash -c "cd ubyssey/static && npm install && gulp"
    volumes:
      - .:/ubyssey.ca

## Starts up static file watcher for Dispatch platform
  yarn:
    build: .
    command: bash -c "cd ../dispatch/dispatch/static/manager && yarn start"
    volumes:
      - /dispatch

## Starts up Django server for ubyssey.ca and Dispatch
  django:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ubyssey.ca
    volumes_from:
      - gulp
      - yarn
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    container_name: ubyssey-dev
