sudo: required

language: python

env:
  - DOCKER_COMPOSE_VERSION=1.10.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo docker-compose django
  - openssl aes-256-cbc -K $encrypted_d55f894abbe8_key -iv $encrypted_d55f894abbe8_iv -in client-secret.json.enc -out client-secret.json -d
  - export PYTHONPATH="${PYTHONPATH}:${TRAVIS_BUILD_DIR}/lib"

services:
  - docker

deploy:
  - provider: gcs
    access_key_id: GOOGIEHS55PVL5M3FUVYGR2Z
    secret_access_key: RkEjoaROiwRIjP0blYUxKIV1nQlnlgUVzcSOPpJw
    bucket: ubyssey-prd-flex
    skip_cleanup: true
    acl: public-read
    local-dir: ${TRAVIS_BUILD_DIR}/gcs
    detect_encoding: true
    cache_control: "max-age=31536000"
    on:
      tags: true
  - provider: gae
    keyfile: client-secret.json
    project: ubyssey-prd-flex
    default: true
    version: ubyssey-flex-${TRAVIS_TAG//./-} # Replace periods with hyphens
    skip_cleanup: true
    on:
      tags: true
